### ISSUE TITLE
XML parse issue 

### ISSUE THREAD

**Issue by kapso** [mvz/happymapper#112]
I have an XML document that contains `&amp;` which if I parse using `MyObject.parse(xml)` returns an error `Nokogiri::XML::SyntaxError (92:15: FATAL: xmlParseEntityRef: no name)`

```
/app/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/document.rb:62:in `read_memory'
/app/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/document.rb:62:in `parse'
/app/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.4/lib/nokogiri/xml.rb:35:in `XML'
/app/vendor/bundle/ruby/2.6.0/gems/nokogiri-happymapper-0.8.1/lib/happymapper.rb:307:in `parse'
```

But when I use the following code (https://github.com/mvz/happymapper/blob/master/lib/happymapper.rb#L307) to parse the same document there's no error and a `Nokogiri::XML::Document` document is returned.

`doc = Nokogiri::XML(xml, nil, nil, Nokogiri::XML::ParseOptions::STRICT, nil)`

I have tried escaping `&amp;` with `&`, but still see the same issue.

**Comment by kapso** [comment]
Fixed this using the following approach -

```ruby
MyObject.with_nokogiri_config { |config| config.options = Nokogiri::XML::ParseOptions::DEFAULT_XML }
MyObject.parse(xml)
```

`Nokogiri::XML::ParseOptions::STRICT` is what causes the issue.
